const title = 'Lorem ipsum dolor sit'

const content = `<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut lacinia vitae risus iaculis blandit. Nunc convallis dolor in elit vehicula, eu egestas ex dignissim. Fusce accumsan varius lorem a convallis. Integer luctus, felis a eleifend aliquet, nisi tellus finibus ante, in tristique augue sem pulvinar tortor. Ut finibus malesuada mi, in ultrices sapien fermentum eu. Ut ut mi augue. Nullam eu augue ac nulla porttitor tincidunt. Ut eu nulla non lorem tempor luctus vel ac turpis. Curabitur a leo lacinia neque pharetra bibendum.</p>

<p>Mauris eu elit at libero gravida gravida. Maecenas venenatis pretium eros, id fermentum erat vestibulum in. Nullam et diam vitae magna accumsan finibus. Phasellus et ligula leo. Quisque rutrum nunc tincidunt, aliquam nulla non, porta tortor. Curabitur non urna ut massa euismod mollis. Proin ut enim vitae massa placerat commodo. Ut posuere urna eu augue faucibus euismod. Nam aliquam nisi facilisis dui blandit pretium. Curabitur et interdum lectus.</p>

<p>Aliquam feugiat mi nisl, at condimentum ex suscipit gravida. Aliquam laoreet orci sit amet massa faucibus vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In at odio sit amet velit rhoncus iaculis. Etiam pellentesque volutpat posuere. Vivamus fermentum sapien porttitor tristique vulputate. Phasellus ut velit massa. Mauris eu nisi vitae felis sagittis mollis. Phasellus accumsan lacus id enim semper, sed bibendum ligula posuere. Maecenas semper eros a tincidunt dictum. Duis vitae erat sapien. Nunc nec neque sed dolor ultrices efficitur.</p>

<p>Suspendisse vel vulputate tortor. Sed in auctor lacus. Etiam sed eros vel orci sodales convallis sed quis nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam tristique aliquet lacus. Aenean luctus nulla orci, ac tincidunt erat eleifend ut. Fusce quis mi in orci semper commodo. Donec tristique, orci in suscipit scelerisque, libero eros semper diam, id placerat libero dui vitae sem. Curabitur faucibus orci vitae dolor mattis, id porta tellus faucibus. Aliquam vitae finibus lectus. Vestibulum semper scelerisque lectus id ornare. Sed sem lorem, facilisis ac metus eget, iaculis cursus massa.</p>

<p>Vestibulum egestas nunc orci, et ornare quam laoreet at. Maecenas ut venenatis tortor, a gravida turpis. Fusce iaculis in diam eget vestibulum. Aenean varius in diam eu ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut suscipit odio. Cras hendrerit fringilla venenatis. Nulla facilisi. Sed vitae bibendum diam, vitae tincidunt sem. Sed neque augue, fermentum id tristique sit amet, vulputate at ligula.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut lacinia vitae risus iaculis blandit. Nunc convallis dolor in elit vehicula, eu egestas ex dignissim. Fusce accumsan varius lorem a convallis. Integer luctus, felis a eleifend aliquet, nisi tellus finibus ante, in tristique augue sem pulvinar tortor. Ut finibus malesuada mi, in ultrices sapien fermentum eu. Ut ut mi augue. Nullam eu augue ac nulla porttitor tincidunt. Ut eu nulla non lorem tempor luctus vel ac turpis. Curabitur a leo lacinia neque pharetra bibendum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut lacinia vitae risus iaculis blandit. Nunc convallis dolor in elit vehicula, eu egestas ex dignissim. Fusce accumsan varius lorem a convallis. Integer luctus, felis a eleifend aliquet, nisi tellus finibus ante, in tristique augue sem pulvinar tortor. Ut finibus malesuada mi, in ultrices sapien fermentum eu. Ut ut mi augue. Nullam eu augue ac nulla porttitor tincidunt. Ut eu nulla non lorem tempor luctus vel ac turpis. Curabitur a leo lacinia neque pharetra bibendum.</p>

<p>Mauris eu elit at libero gravida gravida. Maecenas venenatis pretium eros, id fermentum erat vestibulum in. Nullam et diam vitae magna accumsan finibus. Phasellus et ligula leo. Quisque rutrum nunc tincidunt, aliquam nulla non, porta tortor. Curabitur non urna ut massa euismod mollis. Proin ut enim vitae massa placerat commodo. Ut posuere urna eu augue faucibus euismod. Nam aliquam nisi facilisis dui blandit pretium. Curabitur et interdum lectus.</p>

<p>Aliquam feugiat mi nisl, at condimentum ex suscipit gravida. Aliquam laoreet orci sit amet massa faucibus vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In at odio sit amet velit rhoncus iaculis. Etiam pellentesque volutpat posuere. Vivamus fermentum sapien porttitor tristique vulputate. Phasellus ut velit massa. Mauris eu nisi vitae felis sagittis mollis. Phasellus accumsan lacus id enim semper, sed bibendum ligula posuere. Maecenas semper eros a tincidunt dictum. Duis vitae erat sapien. Nunc nec neque sed dolor ultrices efficitur.</p>

<p>Suspendisse vel vulputate tortor. Sed in auctor lacus. Etiam sed eros vel orci sodales convallis sed quis nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam tristique aliquet lacus. Aenean luctus nulla orci, ac tincidunt erat eleifend ut. Fusce quis mi in orci semper commodo. Donec tristique, orci in suscipit scelerisque, libero eros semper diam, id placerat libero dui vitae sem. Curabitur faucibus orci vitae dolor mattis, id porta tellus faucibus. Aliquam vitae finibus lectus. Vestibulum semper scelerisque lectus id ornare. Sed sem lorem, facilisis ac metus eget, iaculis cursus massa.</p>

<p>Vestibulum egestas nunc orci, et ornare quam laoreet at. Maecenas ut venenatis tortor, a gravida turpis. Fusce iaculis in diam eget vestibulum. Aenean varius in diam eu ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut suscipit odio. Cras hendrerit fringilla venenatis. Nulla facilisi. Sed vitae bibendum diam, vitae tincidunt sem. Sed neque augue, fermentum id tristique sit amet, vulputate at ligula.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut lacinia vitae risus iaculis blandit. Nunc convallis dolor in elit vehicula, eu egestas ex dignissim. Fusce accumsan varius lorem a convallis. Integer luctus, felis a eleifend aliquet, nisi tellus finibus ante, in tristique augue sem pulvinar tortor. Ut finibus malesuada mi, in ultrices sapien fermentum eu. Ut ut mi augue. Nullam eu augue ac nulla porttitor tincidunt. Ut eu nulla non lorem tempor luctus vel ac turpis. Curabitur a leo lacinia neque pharetra bibendum.</p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut lacinia vitae risus iaculis blandit. Nunc convallis dolor in elit vehicula, eu egestas ex dignissim. Fusce accumsan varius lorem a convallis. Integer luctus, felis a eleifend aliquet, nisi tellus finibus ante, in tristique augue sem pulvinar tortor. Ut finibus malesuada mi, in ultrices sapien fermentum eu. Ut ut mi augue. Nullam eu augue ac nulla porttitor tincidunt. Ut eu nulla non lorem tempor luctus vel ac turpis. Curabitur a leo lacinia neque pharetra bibendum.</p>

<p>Mauris eu elit at libero gravida gravida. Maecenas venenatis pretium eros, id fermentum erat vestibulum in. Nullam et diam vitae magna accumsan finibus. Phasellus et ligula leo. Quisque rutrum nunc tincidunt, aliquam nulla non, porta tortor. Curabitur non urna ut massa euismod mollis. Proin ut enim vitae massa placerat commodo. Ut posuere urna eu augue faucibus euismod. Nam aliquam nisi facilisis dui blandit pretium. Curabitur et interdum lectus.</p>

<p>Aliquam feugiat mi nisl, at condimentum ex suscipit gravida. Aliquam laoreet orci sit amet massa faucibus vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; In at odio sit amet velit rhoncus iaculis. Etiam pellentesque volutpat posuere. Vivamus fermentum sapien porttitor tristique vulputate. Phasellus ut velit massa. Mauris eu nisi vitae felis sagittis mollis. Phasellus accumsan lacus id enim semper, sed bibendum ligula posuere. Maecenas semper eros a tincidunt dictum. Duis vitae erat sapien. Nunc nec neque sed dolor ultrices efficitur.</p>

<p>Suspendisse vel vulputate tortor. Sed in auctor lacus. Etiam sed eros vel orci sodales convallis sed quis nisi. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam tristique aliquet lacus. Aenean luctus nulla orci, ac tincidunt erat eleifend ut. Fusce quis mi in orci semper commodo. Donec tristique, orci in suscipit scelerisque, libero eros semper diam, id placerat libero dui vitae sem. Curabitur faucibus orci vitae dolor mattis, id porta tellus faucibus. Aliquam vitae finibus lectus. Vestibulum semper scelerisque lectus id ornare. Sed sem lorem, facilisis ac metus eget, iaculis cursus massa.</p>

<p>Vestibulum egestas nunc orci, et ornare quam laoreet at. Maecenas ut venenatis tortor, a gravida turpis. Fusce iaculis in diam eget vestibulum. Aenean varius in diam eu ullamcorper. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc ut suscipit odio. Cras hendrerit fringilla venenatis. Nulla facilisi. Sed vitae bibendum diam, vitae tincidunt sem. Sed neque augue, fermentum id tristique sit amet, vulputate at ligula.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut lacinia vitae risus iaculis blandit. Nunc convallis dolor in elit vehicula, eu egestas ex dignissim. Fusce accumsan varius lorem a convallis. Integer luctus, felis a eleifend aliquet, nisi tellus finibus ante, in tristique augue sem pulvinar tortor. Ut finibus malesuada mi, in ultrices sapien fermentum eu. Ut ut mi augue. Nullam eu augue ac nulla porttitor tincidunt. Ut eu nulla non lorem tempor luctus vel ac turpis. Curabitur a leo lacinia neque pharetra bibendum.</p>`

module.exports = {
  title,
  content
}
